{ stdenv, fetchurl, python, asciidoc, re2c }:

stdenv.mkDerivation rec {
  name = "ninja-${version}";
  version = "1.7.2.gaad58.kitware.dyndep-1";

  src = fetchurl {
    url = "https://github.com/Kitware/ninja/archive/v${version}.tar.gz";
    sha256 = "1y75k8n3b5qvd8sz85cwdmfwihf5i35zlrbkwi99zz3qxznp3jgs";
  };

  buildInputs = [ python asciidoc re2c ];

  buildPhase = ''
    python configure.py --bootstrap
    asciidoc doc/manual.asciidoc
  '';

  installPhase = ''
    mkdir -p $out/bin
    cp ninja $out/bin/

    mkdir -p $out/share/doc/ninja
    cp doc/manual.asciidoc $out/share/doc/ninja/
    cp doc/manual.html $out/share/doc/ninja/
  '';

  meta = with stdenv.lib; {
    description = "Small build system with a focus on speed";
    longDescription = ''
      Ninja is a small build system with a focus on speed. It differs from
      other build systems in two major respects: it is designed to have its
      input files generated by a higher-level build system, and it is designed
      to run builds as fast as possible.
      Kitware maintains this branch of Ninja in order to provide features
      needed to support Fortran builds but that have not yet been integrated
      upstream.
    '';
    homepage = https://ninja-build.org/;
    license = licenses.asl20;
    platforms = platforms.unix;
    maintainers = [ maintainers.robertodr ];
  };
}
